'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnnouncementsPage

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''announcementTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''announcementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementType As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''announcementBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementBody As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''AddAnnouncementButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAnnouncementButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AnnouncementsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnnouncementsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''editAnnouncementTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editAnnouncementTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''editAnnouncementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editAnnouncementType As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''editAnnouncementBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editAnnouncementBody As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''SaveChangesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveChangesButton As Global.System.Web.UI.WebControls.Button
End Class
