'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnnouncementsPage

    '''<summary>
    '''announcementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''announcementTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''announcementBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementBody As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''addAnnouncementButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAnnouncementButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CreatedAnnouncements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreatedAnnouncements As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
