'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CourseContent1

    '''<summary>
    '''newContentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newContentTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''newContentDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newContentDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''newContentThumbnail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newContentThumbnail As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''newContentDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newContentDocument As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnAddContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddContent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ContentContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
