'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewSubmissionLink

    '''<summary>
    '''submissionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submissionTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''submissionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submissionText As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''openDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents openDateTime As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''closeDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents closeDateTime As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''newSubmissionFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newSubmissionFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnAddNewSubmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewSubmission As Global.System.Web.UI.WebControls.Button
End Class
