'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnnouncementPage

    '''<summary>
    '''announcementTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''announcementsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementsForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sendTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sendTo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkListCoursesProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListCoursesProjects As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''announcementText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementText As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''announcementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementLink As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''announcementSentBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents announcementSentBy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''addAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAnnouncement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AnnouncementsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnnouncementsContainer As Global.System.Web.UI.WebControls.PlaceHolder
End Class
