'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Manager

    Partial Public Class CoursePage1

        '''<summary>
        '''HyperLink1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblCourseName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCourseName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''CourseOverviewContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CourseOverviewContainer As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''CourseResourcesContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CourseResourcesContainer As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''AssignmentsContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssignmentsContainer As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''AcceptReject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AcceptReject As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
