'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Courses1

    '''<summary>
    '''AddCourseForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddCourseForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''coureName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''coureID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''coureDesription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureDesription As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''coureOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureOverview As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''coureStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureStartDate As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''coureEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureEndDate As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''CourseStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CourseStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Selectfactilitators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Selectfactilitators As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''CreateCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateCourse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddNewCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewCourse As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''CoursesContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoursesContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
