'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageUsers

    '''<summary>
    '''load_studentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents load_studentID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Gobtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gobtn As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''SelectedEnrolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedEnrolID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''glano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents glano As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''userFname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userFname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''userLname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userLname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''useremail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents useremail As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''userroletxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userroletxt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''userrole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userrole As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''coureStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureStartDate As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''coureEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coureEndDate As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''EnrollmentStatustxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnrollmentStatustxt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''EnrollmentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnrollmentStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdateUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateUser As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''RemoveUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RemoveUser As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''TableUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlEnrollment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEnrollment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SelectedUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedUserID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''EnrollmentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnrollmentInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CoursesAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoursesAvailable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnrollStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnrollStudent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ApplicationFormPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplicationFormPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ApplicationForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplicationForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CreatedQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreatedQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AcceptApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AcceptApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DeclineApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeclineApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CloseAPl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseAPl As Global.System.Web.UI.WebControls.Button
End Class
